# Generated by Django 5.0 on 2024-01-11 10:14

import app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone_no',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(10), app.validators.validate_phone_no]),
        ),
    ]
